Feature/#39 actualsign in
tsukuba-cojt/ains-frontend pull request #52
Opened 2023-07-05 05:53 UTC by UNIQabes

・src/pages/components/LoginModal.tsx  src/pages/components/SignupModal.tsx に実際のログイン/サインアップ処理を追加した。
・メールアドレス認証などは今の所実装していない
・ログインとサインアップのエラーハンドラーを実装した。

2023-07-05 05:58 UTC, UNIQabes commented
firebaseTestページのsignoutDayoボタンを押せばサインアウトできます。何回もログインして挙動を確認したい時に利用してください

2023-07-07 06:51 UTC, fazerog02 requested changes

2023-07-07 06:51 UTC, fazerog02 commented on src/components/LoginModal.tsx
> +        // ...
ここにemail, passwordを空文字列にリセットする処理がほしいです！
`setEmail("")`みたいな感じ

 それとログインモーダルを非表示にしたいです
`props.onClose()`

2023-07-07 06:51 UTC, fazerog02 commented on src/components/LoginModal.tsx
> +              switchPasswordVisible();
パスワードが可視化されてしまうのでこれは消してほしいです！

2023-07-07 06:51 UTC, fazerog02 commented on src/components/SignupModal.tsx
> +        // ...
loginと同じようにstateの初期化とモーダルを閉じる処理がほしいです！

2023-07-07 06:51 UTC, fazerog02 commented on src/components/SignupModal.tsx
> +              switchPasswordVisible();
` switchPasswordVisible();`は消しておいてください！

2023-07-07 07:33 UTC, fazerog02 approved these changes
LGTM!

2023-07-07 07:33 UTC, merged